// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj1-w2F9a6LuOJt6eNX4YNLLrTDBJXdwM',
    appId: '1:1020446679828:web:96709fabbd14dc39fa9801',
    messagingSenderId: '1020446679828',
    projectId: 'list-tile',
    authDomain: 'list-tile.firebaseapp.com',
    storageBucket: 'list-tile.appspot.com',
    measurementId: 'G-W4CBCZTDV3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoRWmHI03-aA-Tnt6LONibqTb429ybmj0',
    appId: '1:1020446679828:android:99b772b507b79c62fa9801',
    messagingSenderId: '1020446679828',
    projectId: 'list-tile',
    storageBucket: 'list-tile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9lB-62b05UzWowcktuKphd1-rDvSNSEo',
    appId: '1:1020446679828:ios:aa73b8f9d86447adfa9801',
    messagingSenderId: '1020446679828',
    projectId: 'list-tile',
    storageBucket: 'list-tile.appspot.com',
    iosBundleId: 'com.example.homerLoginForm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9lB-62b05UzWowcktuKphd1-rDvSNSEo',
    appId: '1:1020446679828:ios:c2a5b1c81d2ddd98fa9801',
    messagingSenderId: '1020446679828',
    projectId: 'list-tile',
    storageBucket: 'list-tile.appspot.com',
    iosBundleId: 'com.example.homerLoginForm.RunnerTests',
  );
}
